# Generated by Django 3.2.3 on 2021-06-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalarrangement', models.IntegerField()),
                ('men', models.IntegerField()),
                ('women', models.IntegerField()),
                ('children', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=30)),
                ('totalamount', models.CharField(max_length=20)),
                ('billdate', models.DateField()),
                ('billtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='cashpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.IntegerField()),
                ('paidamount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=13)),
                ('phoneno', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phoneno', models.CharField(max_length=15)),
                ('whatsappno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
                ('bookingid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='distributer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='distributerbrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='distributercontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phoneno', models.CharField(max_length=15)),
                ('whatsappno', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='distributorrepresentator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fathername', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='dutytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('shifts', models.CharField(max_length=2)),
                ('vacations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='employeecontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=15)),
                ('whatsappno', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employeeexperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=20)),
                ('leavingreason', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employeeincome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='employeeskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=20)),
                ('certificate', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=10)),
                ('yearexperience', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('arrangement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('catagory', models.CharField(max_length=10)),
                ('detail', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='financialrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('expensesid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.expenses')),
            ],
        ),
        migrations.CreateModel(
            name='instalment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstinstalment', models.IntegerField()),
                ('secondinstalment', models.IntegerField()),
                ('thirdinstalment', models.IntegerField()),
                ('remainingamount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('perheadprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField()),
                ('totalorder', models.IntegerField()),
                ('orderstatus', models.CharField(max_length=20)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.customer')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(max_length=30)),
                ('accountbranch', models.CharField(max_length=45)),
                ('amountpaid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('financialrecordid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.financialrecord')),
            ],
        ),
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=10)),
                ('signinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.signin')),
            ],
        ),
        migrations.CreateModel(
            name='stockavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stockeditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stockorderbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalbill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stockorderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('unitprice', models.IntegerField()),
                ('totalprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stockorderpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paymentmethod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stockreceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=15)),
                ('whatsappno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.AddField(
            model_name='stockorderbooking',
            name='stockorderpayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.stockorderpayment'),
        ),
        migrations.AddField(
            model_name='stockavailable',
            name='stockorderdetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.stockorderdetails'),
        ),
        migrations.AddField(
            model_name='menu',
            name='stockavailableid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.stockavailable'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeecontactid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.employeecontact'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeexperienceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.employeeexperience'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeincomeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.employeeincome'),
        ),
        migrations.AddField(
            model_name='distributer',
            name='distributerbrandid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.distributerbrand'),
        ),
        migrations.AddField(
            model_name='distributer',
            name='distributercontactid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.distributercontact'),
        ),
        migrations.AddField(
            model_name='booking',
            name='eventid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.event'),
        ),
        migrations.AddField(
            model_name='booking',
            name='menuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.menu'),
        ),
    ]
