# Generated by Django 3.2.3 on 2021-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_product_insert'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('Product_image', models.ImageField(upload_to='images/')),
                ('p_price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='product_insert',
        ),
    ]
