# Generated by Django 3.2.3 on 2021-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0005_auto_20210711_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
