# Generated by Django 3.2.3 on 2021-07-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0006_add_to_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_to_cart',
            new_name='addtocart',
        ),
    ]
