# Generated by Django 3.2.3 on 2021-07-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0007_rename_add_to_cart_addtocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quan', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RenameField(
            model_name='addtocart',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='orderel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.req'),
        ),
    ]
