# Generated by Django 3.2.3 on 2021-07-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0009_auto_20210714_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_in',
            old_name='Product_image',
            new_name='image',
        ),
    ]
